config/routes.rb
Rails.application.routes.draw do

  root 'static#index'
  get 'examples', to: 'static#examples', as: :examples

  namespace :widgets do
    get 'preload', to: 'preload#index'
    get 'summary/state', to: 'summary#state'
    get 'summary/single', to: 'summary#single'
    get 'summary/multiple', to: 'summary#multiple'
    get 'summary/statesearch', to: 'summary#statesearch'
    get 'navigator/title', to: 'navigator#title'
    get 'usage/state', to: 'usage#state'
    get 'usage/single', to: 'usage#single'
    get 'usage/multiple', to: 'usage#multiple'
  end

end

app/views/layouts/application.html.slim
doctype html
html lang='en'

  head
    meta charset='utf-8'
    title Trove widget configurator
    = stylesheet_link_tag 'application/application'
    = javascript_include_tag  'application/application'
    = favicon_link_tag '/favicon.ico'
    = csrf_meta_tags

  body

    .container
      .page-header
        ul.nav.nav-pills.pull-right
          li class="#{current_page?(root_path) ? 'active' : 'default'}"= link_to 'Home', root_url
          li class="#{current_page?(examples_path) ? 'active' : 'default'}"= link_to 'Examples', examples_url
        h1= link_to 'Trove widgets', root_path

      p.lead Embed these widgets on your own web page to allow visitors to discover and search Trove content relevant to you.

      p To create a widget: choose a widget type, configure it, click 'Apply' for a preview, then copy and paste the content of the code box into your web page.

      = yield

app/views/layouts/widgets.html.slim
doctype html
html lang='en'

  head
    meta charset='utf-8'
    title Trove widget
    = stylesheet_link_tag 'widgets/application'
    = javascript_include_tag  'widgets/application'

    css:
      html, .widget__header-logo, .search__field, .search__button {
        background-color: #{params[:background]};
      }
      .widget__inner, .search__field {
        border-color: #{params[:border]};
      }
      body {
        color: #{params[:text]};
      }
      p.item__stats, .widget__credits, p.navigator__list-stats, p.usage__list-stats {
        color: #{params[:subtitle]};
      }
      ::-webkit-input-placeholder {
        color: #{params[:subtitle]};
      }
      :-moz-placeholder {
        color: #{params[:subtitle]};
      }
      ::-moz-placeholder {
        color: #{params[:subtitle]};
      }
      :-ms-input-placeholder {
        color: #{params[:subtitle]};
      }
      h1.item__title, h1.navigator__title, h1.usage__title, strong.navigator__list-title, strong.usage__list-title, strong.navigator__list-title a, strong.usage__list-title a {
        color: #{params[:title]}
      }

  body

    = content_tag :div, class: 'widget', data: data_params, role: 'trove-widget__wrapper' do
      .widget__inner style="height:#{params[:height].to_i-42}px;"
        .widget__header
          b #{data_params[:heading]}
          = link_to 'Trove', 'http://trove.nla.gov.au/', title: "#{data_params[:heading]}", target: :blank, class: 'widget__header-logo'
        .widget__body
          .widget__preload role='trove-widget__preload'= yield
          .widget__credits class="widget__credits--#{params[:type]}-#{params[:view]}" #{params[:credits]}